language: node_js
node_js:
    - "0.12"
    - "0.10"
#   - "0.8"     # no longer supported by iconv
#   - "0.6"     # no longer supported by async
    - "stable"
    - "iojs-v3"
services:
    - redis-server
    
# these are required for building on node.js 4.0 / io.js v3
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - "CXX=g++-4.8"
# end: these are required for building on node.js 4.0 / io.js v3
  
after_success:
    - npm run coveralls
sudo: false